# SECTION 13, Data Set Processing

In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
# method-01: split, using sklearn, pytorch, keras
sample_data = np.random.random(size=(100, 5))
train, test = train_test_split(sample_data, train_size=0.8)
# train

In [3]:
# method-02: numpy random
indices = np.random.choice(range(len(sample_data)), size=int(0.8*(len(sample_data))), replace=True)
len(indices)

80

In [4]:
from icecream import ic
some_large_number = [23421421,42155151,25531238,21826139, 32189732, 32103721]

def normalize(x):
    return (x - np.min(x)) / (np.max(x) - np.min(x))

ic(normalize(np.array(some_large_number)))

ic| normalize(np.array(some_large_number)): array([0.07847317, 1.        , 0.18225672, 0.        , 0.50979325,
                                                   0.5055623 ])


array([0.07847317, 1.        , 0.18225672, 0.        , 0.50979325,
       0.5055623 ])

In [5]:
some_small_number = [0.00000231213,  0.0005600321, 0.0000041412892, 0.000987890576, 0.0000578921764]
ic(normalize(np.array(some_small_number)))

ic| normalize(np.array(some_small_number)): array([0.        , 0.56588085, 0.00185592, 1.        , 0.05639333])


array([0.        , 0.56588085, 0.00185592, 1.        , 0.05639333])

In [6]:
some_dense_number = [47238941, 47238946, 47238951, 47238931, 47238949, 47238936]
def standarlize(x):
    return (x - np.mean(x))/ np.std(x)

ic(standarlize(np.array(some_dense_number)))

ic| standarlize(np.array(some_dense_number)): array([-0.18752289,  0.51568795,  1.2188988 , -1.59394459,  0.93761446,
                                                     -0.89073374])


array([-0.18752289,  0.51568795,  1.2188988 , -1.59394459,  0.93761446,
       -0.89073374])

In [7]:
def f(x):
    return (0, 1) # Whether to buy

In [14]:
array = ['Beijing', 'Shanghai', 'Guangzhou', 'Ningxia', 'Chengdu', 'Shanghai', 'Beijing']

def one_hot(elements):
    pure = list(set(elements))
    
    vectors = []

    for i in elements:
        vec = [0] * len(pure)
        vec[pure.index(i)] = 1
        vectors.append(vec)

    return vectors

print(one_hot(array))

[[0, 0, 0, 1, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 1, 0]]


In [9]:
x = [1231, 12314, 4341, 1542, 4123, 4512, 3213, 1241, 1231, 6842]
x = np.array(normalize(x))

weights = np.random.random(size=(10, 3))

In [10]:
logits = np.dot(x, weights)

## SOFTMAX

In [11]:
def softmax(x):
    x = np.array(x)
    x -= np.max(x)
    return np.exp(x) / np.sum(np.exp(x))

ic(softmax(logits))

ic| softmax(logits): array([0.32385024, 0.27287912, 0.40327064])


array([0.32385024, 0.27287912, 0.40327064])

In [12]:
def cross_entropy(yhat, y):
    return -np.sum(y_i * np.log(yhat_i) for y_i, yhat_i in zip(y, yhat))

In [13]:
y = [0, 1, 0]
ic(cross_entropy(softmax(logits),y))

/var/folders/h4/7cr1cmpn7v5b3x20_9wz8m740000gn/T/ipykernel_93306/3167118538.py:2: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return -np.sum(y_i * np.log(yhat_i) for y_i, yhat_i in zip(y, yhat))
ic| cross_entropy(softmax(logits

),y): 1.2987263790899837


1.2987263790899837